services:
  - type: web
    name: mango-pesticide-detector-backend
    env: python
    region: oregon
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/health

  - type: web
    name: mango-pesticide-detector-frontend
    env: static
    region: oregon
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
